joinMessages:
  - "&7&m----------------------------"
  - "&aTest Server &7(Hub-01)"
  - ""
  - "&eDiscord: discord.gg/test"
  - "&7&m----------------------------"

scoreboard:
  title: "&9Test &7[Hub-01]"
  lines:
    - "&7&m----------------------------"
    - "&bOnline: &f{online}"
    - " "
    - "&bRank: &f{rank}"
    - " "
    - "&7&m----------------------------"
  linesQueued:
    - "&7&m----------------------------"
    - "&bOnline: &f{online}"
    - " "
    - "&bRank: &f{rank}"
    - " "
    - "&bQueue: &f{queueName}"
    - "&bPosition: &f{position}/{total}"
    - "&7&m----------------------------"

#for the selector menu
selector:
  title: "Choose a Server"
  size: 27
  invSlot: 0
  clickable:
    name: "&9Select a Server"
    lore:
      - "&7Click to select a server!"
    material: BOOK
    data: 0
  items:
    test:
      slot: 0
      displayName: "&9Test"
      lore:
        - "&7Test"
      data: 0
      material: REDSTONE
      command: "joinqueue Test"

#other items that you may want to add
items:
  lobbySelector:
    name: "&bLobby Selector"
    lore:
      - "&7Select a Lobby"
    item: NETHER_STAR
    data: 0
    useAction: true
    slot: 8
    command:
      - "openmenu LobbySelector"

cosmeticButtons:
  particles:
    item: REDSTONE
    name: "&bParticles"
    data: 0
    lore:
      - "&7Click to view particles!"
  armor:
    item: LEATHER_CHESTPLATE
    name: "&bArmor"
    data: 0
    lore:
      - "&7Click to view all armors!"

cosmetics:
  owner:
    displayName: "&4Owner &7Armor"
    r: 255
    g: 0
    b: 6
    item: LEATHER_CHESTPLATE
    data: 0
    type: "ARMOR"
    permission: "cosmetics.owner"